---
id: Text_Flowed
name: Text_Flowed
full: Flowed text library
description: |
  A library that provides common methods for manipulating text using the encoding described in RFC 3676 ('flowed' text).
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Text_Flowed
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha3
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/util: ^3
  optional:
    composer:
      horde/test: ^3
